2018-08-23 10:12:47,819 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-23 10:13:21,770 ERROR: Exception on / [POST] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 27, in index
    language = guess_language(form.post.data)
NameError: name 'guess_language' is not defined
2018-08-23 10:17:35,299 ERROR: Exception on / [POST] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 27, in index
    if form.validate_on_submit():
NameError: name 'guess_language' is not defined
2018-08-23 10:17:45,245 ERROR: Exception on /index [POST] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 27, in index
    if form.validate_on_submit():
NameError: name 'guess_language' is not defined
2018-08-23 10:22:35,681 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-23 10:26:04,770 ERROR: Exception on /index [POST] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 28, in index
    language = guess_language(form.post.data)
NameError: name 'guess_language' is not defined
2018-08-23 10:28:28,042 ERROR: Exception on /index [POST] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 28, in index
    #language = guess_language(form.post.data)
NameError: name 'guess_language' is not defined
2018-08-23 10:29:50,885 ERROR: Exception on /index [POST] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 28, in index
    '''#language = guess_language(form.post.data)
NameError: name 'guess_language' is not defined
2018-08-23 11:49:15,030 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-23 13:50:03,734 ERROR: Exception on /index [POST] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 27, in index
    language = guess_language(form.post.data)
NameError: name 'guess_language' is not defined
2018-08-27 23:53:29,353 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
