2018-08-22 08:12:06,971 ERROR: Exception on /search [GET] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 131, in search
    posts, total = post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
NameError: name 'post' is not defined
2018-08-22 23:02:41,417 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-22 23:05:15,009 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-23 00:38:45,531 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-23 00:45:33,488 ERROR: Exception on /search [GET] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 131, in search
    posts, total = post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
NameError: name 'post' is not defined
2018-08-23 01:00:31,977 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-23 01:28:06,792 ERROR: Exception on /index [POST] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 27, in index
    language = guess_language(form.post.data)
NameError: name 'guess_language' is not defined
2018-08-23 01:32:00,243 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-23 01:35:24,973 ERROR: Exception on /index [POST] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 27, in index
    language = guess_language(form.post.data)
NameError: name 'guess_language' is not defined
2018-08-23 03:41:51,013 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-23 03:42:01,500 ERROR: Exception on /index [POST] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 27, in index
    language = guess_language(form.post.data)
NameError: name 'guess_language' is not defined
2018-08-23 03:48:37,498 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-23 03:50:18,370 ERROR: Exception on /index [POST] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 27, in index
    language = guess_language(form.post.data)
NameError: name 'guess_language' is not defined
2018-08-23 03:58:43,895 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-23 03:59:24,360 ERROR: Exception on /index [POST] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 27, in index
    language = guess_language(form.post.data)
NameError: name 'guess_language' is not defined
